# Generated by Django 4.1.7 on 2023-03-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='session_code',
            field=models.CharField(default='d78aa2', editable=False, max_length=6),
        ),
    ]
