# Generated by Django 4.1.7 on 2023-03-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='played_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='session_code',
            field=models.CharField(default='2165af', editable=False, max_length=6),
        ),
    ]
