# Generated by Django 4.1.7 on 2023-03-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
