# Generated by Django 4.1.7 on 2023-03-09 18:28

import api.models.game_session
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gamesession_session_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='session_code',
            field=models.CharField(default=api.models.game_session.GameSession.session_name_default, max_length=6),
        ),
    ]
