# Generated by Django 4.1.7 on 2023-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='questions',
            field=models.ManyToManyField(to='api.question'),
        ),
    ]
