# Generated by Django 4.1.7 on 2023-03-10 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gamesession_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(blank=True, through='api.Player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='questions',
            field=models.ManyToManyField(blank=True, to='api.question'),
        ),
    ]
