# Generated by Django 4.1.7 on 2023-03-11 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gamesession_active_question_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
