# Generated by Django 4.1.7 on 2023-03-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_response_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gamesession'),
        ),
    ]
