# Generated by Django 4.1.7 on 2023-03-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_response_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Player_Response',
        ),
    ]
