# Generated by Django 4.1.7 on 2023-03-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_response_player_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player_Response',
            new_name='PlayerResponse',
        ),
    ]
