# Generated by Django 4.1.7 on 2023-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_player_response_playerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerresponse',
            name='delta',
            field=models.IntegerField(null=True),
        ),
    ]
