# Generated by Django 4.1.7 on 2023-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_playerresponse_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresponse',
            name='delta',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
